# Generated by Django 3.1.2 on 2020-11-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.ImageField(blank=True, upload_to='movie'),
        ),
    ]
